### PR TITLE
CPO & SimPO add label_smoothing

### PR DESCRIPTION
**Pull request by Mecoli1219**
## Summary

Add label_smoothing support for CPO and SimPO so that they align with the huggingface [interface](https://github.com/huggingface/trl/blob/b668048fe1931c57796ad5ae3f10852337ce7565/trl/trainer/cpo_trainer.py#L645C1-L658C14). 

## Testing Done
- [x] Something wrong with the unit test. I'll have to fix it

- Hardware Type: <BLANK>
- [x] run `make test` to ensure correctness
- [x] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

### CODE REVIEW

**Review by shivam15s — APPROVED** [review]
lgtm

**Review by shivam15s — CHANGES_REQUESTED** [review]
waiting for tests to pass

**Comment by Mecoli1219** [comment]
@shivam15s Are the test failures related to this PR? I think something is wrong with modal.

**Comment by shivam15s** [comment]
The modal tests aren't configured for public forks. Those failing is expected!

**Comment by shivam15s** [comment]
Thanks for the PR, merging 🚀

**Review by shivam15s — APPROVED** [review]

**Pull request merged**
