### PR TITLE
Refactor/benchmarking visualizer

### LINKED ISSUE #211: Refactor: Benchmark visualizer
## Issue

Current visualizations for benchmarks are not ideal, since versioning `.ipynb` files is rather difficult, also changing code to view a different visualization makes the changes rather common, resulting in extra changes each commit.

## Proposal

Change the current `.ipynb` version to a classic python script, configurable through command line arguments, this script also can save the images to a folder, that is added to `.gitignore` so it's not commited by mistake.

### PR DESCRIPTION
**Pull request by S1ro1**
## Summary
Implements a new script, `benchmark/benchmarks_visualizer.py`, that substitues the functionality provided by current `benchmark/benchmarks_visualizer.ipynb`. Resolves #211 .

## Details
```console
$ python3 benchmarks_visualizer.py --help
usage: benchmarks_visualizer.py [-h] --kernel-name KERNEL_NAME --metric-name METRIC_NAME --kernel-operation-mode KERNEL_OPERATION_MODE [--display] [--overwrite]

options:
  -h, --help            show this help message and exit
  --kernel-name KERNEL_NAME
                        Kernel name to benchmark
  --metric-name METRIC_NAME
                        Metric name to visualize (speed/memory)
  --kernel-operation-mode KERNEL_OPERATION_MODE
                        Kernel operation mode to visualize (forward/backward/full)
  --display             Display the visualization
  --overwrite           Overwrite existing visualization, if none exist this flag has no effect as one are always created
  ```

## Testing Done

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [ ] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

### CODE REVIEW

**Comment by S1ro1** [comment]
cc @ByronHsu, here's the draft that I thought of, feel free to say any notes, if so, will properly document/redo it tommorow.

**Comment by ByronHsu** [comment]
lgtm

**Comment by S1ro1** [comment]
Okay, will cleanup the code, add comments, resp. adjust `CONTRIBUTING.md` and should be marked as ready.

**Comment by S1ro1** [comment]
@ByronHsu should be ready to merge, did docstrings and edited contributing guidelines to reflect the new version.

**Review by lancerts — APPROVED** [review]

**Pull request merged**
