### PR TITLE
Test for compatibility with torch.compile

### PR DESCRIPTION
**Pull request by tyler-romero**
## Summary
Add test to defend against incompatibilities between torch.compile and LigerKernel.

Notably, LigerKernel must be applied *after* torch.compile(model) is called. Or there will be a compile error. The other way around is correct.


## Testing Done
This PR adds a test that repros this failure, and will fail if the torch.compile + LigerKernel breaks.
```
> HF_DATASETS_OFFLINE=1 python -m pytest --disable-warnings test/convergence -k "test_mini_model_with_torch_compile"
====================================================================================================================================================== short test summary info =======================================================================================================================================================
FAILED test/convergence/test_mini_models.py::test_mini_model_with_torch_compile[mini_qwen2] - torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
============================================================================================================================ 1 failed, 5 passed, 1 skipped, 28 deselected, 1 warning in 128.15s (0:02:08) ============================================================================================================================
```
yet strangely, when run on its own:
```
> HF_DATASETS_OFFLINE=1 python -m pytest --disable-warnings test/convergence -k "test_mini_model_with_torch_compile and mini_qwen2"
======================================================================================================================================================== test session starts =========================================================================================================================================================
platform linux -- Python 3.10.13, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/tromero/workspace/Liger-Kernel
plugins: devtools-0.12.2
collected 35 items / 34 deselected / 1 selected                                                                                                                                                                                                                                                                                      

test/convergence/test_mini_models.py .                                                                                                                                                                                                                                                                                         [100%]

============================================================================================================================================ 1 passed, 34 deselected, 1 warning in 24.83s ============================================================================================================================================
```

- Hardware Type: 4090
- [x] run `make test` to ensure correctness
- [x] run `make checkstyle` to ensure code style
- [x] run `make test-convergence` to ensure convergence

### CODE REVIEW

**Comment by tyler-romero** [comment]
I'm not available to put together a real fix for this bug (at least until next week), but anyone can use this PR however they want in the process of fixing.

**Comment by tyler-romero** [comment]
Closing b/c reordering torch compile and liger monkeypatch solves.

**Comment by tyler-romero** [comment]
todo: check that liger kernels are actually substituted if applied after torch.compile()

**Comment by lancerts** [comment]
@tyler-romero what is the status of this PR? Is it still active? ty

**Comment by tyler-romero** [comment]
I'll close it for now

**Pull request closed without merging**
