### PR TITLE
Add FusedLinerCrossEntropy support for Mistral

### PR DESCRIPTION
**Pull request by Tcc0403**
## Summary

This PR adds FusedLinearCrossEntropy support for mistral to resolve issue #100 .

## Details
The `lce_forward` implementation is modified from the [`forward`](https://github.com/huggingface/transformers/blob/main/src/transformers/models/mistral/modeling_mistral.py#L987) method of `MistralForCausalLM` and llama/qwen2 implementations in this repo.

Since the parameters `fused_linear_cross_entropy` and `cross_entropy` cannot both be true, `fused_linear_cross_entropy` has to be explicitly set to `False` in `test_mini_models.py`, to avoid failing convergence
test due to setting both True.

In `test_mini_models_no_logits.py`, I add two extra tests for mistral to ensure that FusedLinearCrossEntropy part in mistral is tested.

## Testing Done

I don't have a GPU with enough memory to fully run `make test`, so I only did `test_trainer_integration.py` and `test_transformers_monkey_patch.py` for this part. Hopefully someone can test it for me.

- Hardware Type: RTX-3080-10G
- [ ] run `make test` to ensure correctness
- [x] run `make checkstyle` to ensure code style
- [x] run `make test-convergence` to ensure convergence
```bash
❯ pytest test/transformers/test_trainer_integration.py
===================================== test session starts =====================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/tcc/Liger-Kernel
plugins: hydra-core-1.3.2, typeguard-4.2.1, anyio-4.3.0
collected 3 items

test/transformers/test_trainer_integration.py ...                                       [100%]

====================================== 3 passed in 6.50s ======================================
❯ pytest test/transformers/test_transformers_monkey_patch.py
===================================== test session starts =====================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/tcc/Liger-Kernel
plugins: hydra-core-1.3.2, typeguard-4.2.1, anyio-4.3.0
collected 1 item

test/transformers/test_transformers_monkey_patch.py .                                   [100%]

====================================== 1 passed in 1.78s ======================================
```
```bash
❯ make checkstyle
flake8 .; flake8_status=$?; \
isort .; isort_status=$?; \
black .; black_status=$?; \
if [ $flake8_status -ne 0 ] || [ $isort_status -ne 0 ] || [ $black_status -ne 0 ]; then \
        exit 1; \
fi
Skipped 2 files
All done! ✨ 🍰 ✨
53 files left unchanged.
```
```bash
❯ make test-convergence
HF_DATASETS_OFFLINE=1 pytest --disable-warnings test/convergence
===================================== test session starts =====================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/tcc/Liger-Kernel
collected 12 items

test/convergence/test_mini_models.py ........                                           [ 66%]
test/convergence/test_mini_models_no_logits.py ....                                     [100%]

================================ 12 passed in 81.15s (0:01:21) ================================
```

### CODE REVIEW

**Comment by lancerts** [comment]
Thanks for the contribution. @shimizust can we help to perform a full test?

**Comment by Tcc0403** [comment]
Also, qwen2 is only tested in `test_mini_models.py`, which sets `fused_linear_cross_entropy` to False. Perhaps it also needs to be tested in `test_mini_models_no_logits.py`?

**Comment by ByronHsu** [comment]
@Tcc0403 yeah that is missing. can you create a tix and help on that?

**Comment by ByronHsu** [comment]
> btw is it a typo in mixtral part [Line 100](https://github.com/linkedin/Liger-Kernel/blob/main/src/liger_kernel/transformers/monkey_patch.py#L100)
> 
> ```
> modeling_mixtral.MistralRMSNorm = LigerRMSNorm
> ```
> 
> instead of
> 
> ```
> modeling_mixtral.MixtralRMSNorm = LigerRMSNorm
> ```

feel free to create another pr to fix

**Review by ByronHsu — APPROVED** [review]
Tests passed on my A100. Thanks for the contribution. Added https://github.com/linkedin/Liger-Kernel/issues/104

**Pull request merged**
