### PR TITLE
added `reduction` argument in Cross Entropy Kernel

### PR DESCRIPTION
**Pull request by Ankur-singh**
This PR addresses #83 

Simplified approach to add `reduction` in LigerCrossEntropyFunction.

## Details
Based on the reduction, calculate the `loss` using following logic. 

```python 
if reduction == "mean":
    loss = torch.sum(loss_1d) / n_non_ignore
elif reduction == "sum":
    loss = torch.sum(loss_1d)
```

This approach requires not change to the kernel function itself. Additionally, in my brief testing, I don't see any performance drop because of `torch.sum`. 

## Testing
Added `reduction` parameter to all unit tests. I was not able run all unit test as I only have an 8GB graphics card. 

- Hardware Type: RTX 3060 Ti - 8GB

- [X] run `make test` to ensure correctness 
- [X] run `make checkstyle` to ensure code style
- [X] run `make test-covergence` to ensure convergence

```bash
> make test
python -m pytest --disable-warnings test/ --ignore=test/convergence
=============================================== test session starts =============================================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ankur/Developer/github.com/Liger-Kernel
configfile: pyproject.toml
plugins: anyio-4.4.0
collected 663 items                          
..............................................
test/transformers/test_swiglu.py::test_correctness_functional[dtype1-10000.0-0.01-9-7-41] PASSED                                                                                                           [ 99%]
test/transformers/test_trainer_integration.py::test_import PASSED                                                                                                                                          [ 99%]
test/transformers/test_transforemrs.py::test_import_from_root PASSED                                                                                                                                       [ 99%]
test/triton/test_triton_monkey_patch.py::test_import_from_root PASSED                                                                                                                                      [ 99%]
test/triton/test_triton_monkey_patch.py::test_import_custom_cache_manager PASSED                                                                                                                           [100%]

====================================== 395 passed, 268 skipped, 49 warnings in 174.01s (0:02:54) ==================================================
```

```bash
> make checkstyle             
flake8 .; flake8_status=$?; \
isort .; isort_status=$?; \
black .; black_status=$?; \
if [ $flake8_status -ne 0 ] || [ $isort_status -ne 0 ] || [ $black_status -ne 0 ]; then \
        exit 1; \
fi
Skipped 1 files
All done! ✨ 🍰 ✨
74 files left unchanged.
```

```bash
> make test-convergence 
HF_DATASETS_OFFLINE=1 python -m pytest --disable-warnings test/convergence
================================================= test session starts =====================================================
platform linux -- Python 3.12.5, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ankur/Developer/github.com/Liger-Kernel
configfile: pyproject.toml
plugins: anyio-4.4.0
collecting ... 
------------------------------------------------------------- live log collection ------------------------------------------------------------
INFO     datasets:config.py:59 PyTorch version 2.4.1 available.
collected 30 items                                                                                                                                                                                               

test/convergence/test_mini_models.py::test_mini_model[mini_gemma1-32-0.0001-dtype0-1e-08-0.0006-0.005-1e-05-0.005-1e-05] PASSED                                                                            [  3%]
test/convergence/test_mini_models.py::test_mini_model[mini_gemma1-32-0.0001-dtype1-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                               [  6%]
test/convergence/test_mini_models.py::test_mini_model[mini_gemma1.1-32-0.0001-dtype2-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                           [ 10%]
test/convergence/test_mini_models.py::test_mini_model[mini_gemma1.1-32-0.0001-dtype3-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                             [ 13%]
test/convergence/test_mini_models.py::test_mini_model[mini_gemma2-32-0.0001-dtype4-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                             [ 16%]
test/convergence/test_mini_models.py::test_mini_model[mini_gemma2-32-0.0001-dtype5-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                               [ 20%]
test/convergence/test_mini_models.py::test_mini_model[mini_llama3-32-0.0001-dtype6-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                             [ 23%]
test/convergence/test_mini_models.py::test_mini_model[mini_llama3-32-0.0001-dtype7-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                               [ 26%]
test/convergence/test_mini_models.py::test_mini_model[mini_mistral-32-0.0001-dtype8-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                            [ 30%]
test/convergence/test_mini_models.py::test_mini_model[mini_mistral-32-0.0001-dtype9-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                              [ 33%]
test/convergence/test_mini_models.py::test_mini_model[mini_qwen2-32-0.0001-dtype10-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                             [ 36%]
test/convergence/test_mini_models.py::test_mini_model[mini_qwen2-32-0.0001-dtype11-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                               [ 40%]
test/convergence/test_mini_models.py::test_mini_model[mini_phi3-32-0.0001-dtype12-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                              [ 43%]
test/convergence/test_mini_models.py::test_mini_model[mini_phi3-32-0.0001-dtype13-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                                [ 46%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_llama3-32-0.0001-dtype0-1e-08-2e-05-0.0001-1e-05-0.005-1e-05] PASSED                                                                  [ 50%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_llama3-32-0.0001-dtype1-0.005-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                     [ 53%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_qwen2-32-0.0001-dtype2-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                    [ 56%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_qwen2-32-0.0001-dtype3-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                      [ 60%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_phi3-32-0.0001-dtype4-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                     [ 63%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_phi3-32-0.0001-dtype5-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                       [ 66%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_mistral-32-0.0001-dtype6-1e-08-1e-05-0.005-1e-05-0.005-1e-05] PASSED                                                                  [ 70%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_mistral-32-0.0001-dtype7-1e-08-1e-05-0.01-1e-05-0.01-1e-05] PASSED                                                                    [ 73%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_mixtral-32-0.0001-dtype8-0.0005-0.0001-0.005-1e-05-0.01-1e-05] PASSED                                                                 [ 76%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_mixtral-32-0.0001-dtype9-1e-08-1e-05-0.1-1e-05-0.01-1e-05] PASSED                                                                     [ 80%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_gemma1-32-0.0001-dtype10-1e-08-0.0001-0.005-1e-05-0.005-1e-05] PASSED                                                                 [ 83%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_gemma1-32-0.0001-dtype11-0.01-0.0001-0.2-1e-05-0.01-1e-05] PASSED                                                                     [ 86%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_gemma1.1-32-0.0001-dtype12-1e-08-0.0001-0.005-1e-05-0.005-1e-05] PASSED                                                               [ 90%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_gemma1.1-32-0.0001-dtype13-0.01-0.0001-0.2-1e-05-0.01-1e-05] PASSED                                                                   [ 93%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_gemma2-32-0.0001-dtype14-1e-08-0.0001-0.005-1e-05-0.005-1e-05] PASSED                                                                 [ 96%]
test/convergence/test_mini_models_no_logits.py::test_mini_model[mini_gemma2-32-0.0001-dtype15-0.01-0.0001-0.2-1e-05-0.01-1e-05] PASSED                                                                     [100%]

=========================================== 30 passed, 1 warning in 262.65s (0:04:22) =================================================
```

## Question
cc @ByronHsu @shivam15s 
In PR #153, the kernel code is being updated. Any particular reason for it? I'm new to Liger so this might be a dumb question, but I would really love to know the thought process behind and if there are any advantages.

### CODE REVIEW

**Comment by ByronHsu** [comment]
cc @shivam15s who is also working on this

**Comment by Ankur-singh** [comment]
> cc @shivam15s who is also working on this

Yes, I’ve reviewed his PR and I’m curious about the reasons behind modifying the kernel instead of addressing the changes at the PyTorch level. I haven’t observed any performance degradation so far, but I plan to test both approaches to better understand any potential differences.

**Comment by Tcc0403** [comment]
I was working on it too, but I accidentally closed my PR #140 because of syncing on wrong branch😅. [Here](https://github.com/Tcc0403/Liger-Kernel/blob/cross-entropy/src/liger_kernel/ops/cross_entropy.py) is my branch, not updated since then though.

This approach is similar to mine, but you also need to take care of gradient calculation in the kernel, or it won't pass the gradient parts in unit tests.

A walkaround solution is simply setting n_non_ignore to 1 in case 'sum', then kernel will do the correct calculation.

To implement case 'none', just set n_non_ignore to 1 too and return loss_1d directly. Remember to block the gradient parts in unit tests because the output is not a scaler.

Some concerns about this approach are also addressed in my PR.

**Comment by Ankur-singh** [comment]
Thank you @Tcc0403 for pointing out the issues and highlighting the difference. 

> you also need to take care of gradient calculation in the kernel, or it won't pass the gradient parts in unit tests.

In my local testing, all the test seems to pass so I assumed that backward pass is also working as expected. How can I make sure the gradient calculation is done correctly? Ideally, the unit tests should fail if gradient is wrong. Am I missing something?

**Comment by Tcc0403** [comment]
Make sure you actually test cross entropy, unit tests for cross entropy are mostly skipped if you don't have 16GB+ GPU memory.

You can comment restrictions out and test with smaller shapes. Here's what I usually do.
```python
@pytest.mark.parametrize(
    "B, T, V",
    [
        # (2, 4096, 32000),  # llama2, mistral
        # (2, 4096, 32000),  # llama2, mistral
        # (1, 4096, 128256),  # llama3
        # # weird shapes
        # (3, 423, 32000),
        (2, 4096, 3200),
        (3, 423, 3200),
    ],
)
...
# @pytest.mark.skipif(
#     torch.cuda.get_device_properties(0).total_memory < 16 * 1000 * 1000 * 1000,
#     reason="Needs 16GB+ GPU memory.",
# )
def test_correctness(B, T, V, reduction, scalar, dtype, atol, rtol):
    liger_ce = LigerCrossEntropyLoss(reduction=reduction)
    _test_correctness_once(liger_ce, B, T, V, scalar, dtype, atol, rtol)
```
I pulled this pr and it doesn't work. You might miss some arguments when changing test files. 
```
E       TypeError: _test_correctness_once() missing 1 required positional argument: 'rtol'

test/transformers/test_cross_entropy.py:233: TypeError
```

**Comment by ByronHsu** [comment]
duplicated with https://github.com/linkedin/Liger-Kernel/pull/153

**Pull request closed without merging**
