### PR TITLE
(fix) fix pyproject.toml

### PR DESCRIPTION
**Pull request by wizyoung**
## Summary
In https://github.com/linkedin/Liger-Kernel/pull/218, I fixed the `tool.setuptools.packages.find` field and tested it only in editable mode with `pip install -e .`. However, in production mode with `pip install .`, only the env_report.py file is copied to the Python site-packages directory. To fix this, adding "liger_kernel.*" to the include list will ensure that setuptools correctly includes all subpackages within liger_kernel.

## Testing Done

- Hardware Type: <BLANK>
- [ ] run `make test` to ensure correctness
- [ ] run `make checkstyle` to ensure code style
- [ ] run `make test-convergence` to ensure convergence

### CODE REVIEW

**Review by ByronHsu — COMMENTED** [review]
```bash
jobuser [ ~/resources/Liger-Kernel ]$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://lerna.tools.corp.linkedin.com/pypi/simple/
Processing /home/jobuser/resources/Liger-Kernel
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: torch>=2.1.2 in /home/jobuser/.local/lib/python3.10/site-packages (from liger_kernel==0.2.1) (2.4.0+cu118)
Requirement already satisfied: triton>=2.3.0 in /home/jobuser/.local/lib/python3.10/site-packages (from liger_kernel==0.2.1) (3.0.0)
Requirement already satisfied: transformers>=4.42.0 in /home/jobuser/.local/lib/python3.10/site-packages (from liger_kernel==0.2.1) (4.44.2)
Requirement already satisfied: filelock in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (3.10.7)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (4.8.0)
Requirement already satisfied: sympy in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (1.13.2)
Requirement already satisfied: networkx in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (3.3)
Requirement already satisfied: jinja2 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (3.1.2)
Requirement already satisfied: fsspec in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.20.5 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/jobuser/.local/lib/python3.10/site-packages (from torch>=2.1.2->liger_kernel==0.2.1) (11.8.86)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /home/jobuser/.local/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (0.24.6)
Requirement already satisfied: numpy>=1.17 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (23.2)
Requirement already satisfied: pyyaml>=5.1 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (6.0.1)
Requirement already satisfied: regex!=2019.12.17 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (2022.7.25)
Requirement already satisfied: requests in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (2.31.0)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /home/jobuser/.local/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (0.19.1)
Requirement already satisfied: safetensors>=0.4.1 in /home/jobuser/.local/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (0.4.4)
Requirement already satisfied: tqdm>=4.27 in /home/jobuser/.local/lib/python3.10/site-packages (from transformers>=4.42.0->liger_kernel==0.2.1) (4.66.5)
Requirement already satisfied: MarkupSafe>=2.0 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from jinja2->torch>=2.1.2->liger_kernel==0.2.1) (2.1.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from requests->transformers>=4.42.0->liger_kernel==0.2.1) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from requests->transformers>=4.42.0->liger_kernel==0.2.1) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from requests->transformers>=4.42.0->liger_kernel==0.2.1) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /home/jobuser/build/openconnect-lib-core-image/environments/satellites/python/lib/python3.10/site-packages (from requests->transformers>=4.42.0->liger_kernel==0.2.1) (2022.12.7)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/jobuser/.local/lib/python3.10/site-packages (from sympy->torch>=2.1.2->liger_kernel==0.2.1) (1.3.0)
Building wheels for collected packages: liger_kernel
  Building wheel for liger_kernel (pyproject.toml) ... done
  Created wheel for liger_kernel: filename=liger_kernel-0.2.1-py3-none-any.whl size=50843 sha256=cadb95333c0d39b74d57bef4635460142f3a4253ed94a02fce888ec03fbdf65b
  Stored in directory: /tmp/pip-ephem-wheel-cache-j90ca3ma/wheels/8f/93/24/805daa90e17d8101ddc39b0a5a9e73c3585c36d6222637c307
Successfully built liger_kernel
DEPRECATION: openconnect-lib-core 0.2.60-SNAPSHOT has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of openconnect-lib-core or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: liger_kernel
Successfully installed liger_kernel-0.2.1

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: /export/apps/python/3.10/bin/python3 -m pip install --upgrade pip
jobuser [ ~/resources/Liger-Kernel ]$ python
Python 3.10.14 (main, May 14 2024, 22:06:22) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import liger_kernel
>>> 
```

For some reason, without the fixes, i can still install and import correctly. What env are you running on?

**Comment by ByronHsu** [comment]
even without https://github.com/linkedin/Liger-Kernel/pull/218, i can install correctly.
i think it should work even before #218. Otherwise, the CI will fail? Maybe we are on different environment? cc @yundai424

**Comment by lancerts** [comment]
> even without #218, i can install correctly. i think it should work even before #218. Otherwise, the CI will fail? Maybe we are on different environment? cc @yundai424

use pip install liger
```
>>> from liger_kernel.transformers import LigerFusedLinearCrossEntropyLoss
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LigerFusedLinearCrossEntropyLoss' from 'liger_kernel.transformers' (/home/lancerts/miniconda3/envs/wsl-dev/lib/python3.11/site-packages/liger_kernel/transformers/__init__.py)
```

**Comment by ByronHsu** [comment]
@lancerts that is because https://github.com/linkedin/Liger-Kernel/pull/210 is merged after v0.2.1. Different issue

**Comment by lancerts** [comment]
> @lancerts that is because #210 is merged after v0.2.1. Different issue

Oh, i thought it was in v021... my bad :P

**Comment by wizyoung** [comment]
my env:
```
Operating System: Linux-5.10.0-1.0.0.28-x86_64-with-glibc2.27
Python version: 3.9.19
PyTorch version: 2.3.1+cu121
CUDA version: 12.1
Triton version: 2.3.1
Transformers version: 4.45.0.dev0
```
Actually 0.2.1 works fine in my env, but the nightly version fails to import. After examining the pyproject.toml file and debugging for a while, I discovered that the `tool.setuptools.packages.find` blocked file copying.
To reproduce it again:

```python
❯ ipython                                                                                                                                            14s
iPython 3.9.19 | packaged by conda-forge | (main, Mar 20 2024, 12:50:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import liger_kernel

In [2]: from liger_kernel.transformers.rope import liger_rotary_pos_emb
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from liger_kernel.transformers.rope import liger_rotary_pos_emb
```
```bash
❯ ls /root/miniconda3/lib/python3.9/site-packages/liger_kernel                                                                                     2m 0s
env_report.py  __pycache__
```

**Comment by ByronHsu** [comment]
cc @AndreSlavescu ^^ can you take a look

**Comment by S1ro1** [comment]
Joining here, having weird issues with the editable install as well, can't find a minimaln reproduction tho. Something is off though.

**Comment by AndreSlavescu** [comment]
> ```shell
> ls /root/miniconda3/lib/python3.9/site-packages/liger_kernel 
> ```

Looking into it

**Comment by AndreSlavescu** [comment]
Yeah I think the change should fix the issue with nightly and main release on pypi. Package structure can't be determined in current state, which seems to be an issue.

**Comment by AndreSlavescu** [comment]
Env Settings:
```
python 3.9
```

Tested on following pypi packages:
liger-kernel main release
liger-kernel-nightly release

Tested on source build:
both with change and without change work fine.

This is my small script for repro:

```python
import os
import sys
import importlib

def test_liger_kernel_imports(version):
    print(f"liger_kernel version: {version}")
    
    try:
        import liger_kernel
        print("imported liger_kernel successfully")
        print(f"liger_kernel.__file__: {liger_kernel.__file__}")
        print(f"liger_kernel.__path__: {liger_kernel.__path__}")
        print(f"sys.modules['liger_kernel']: {sys.modules['liger_kernel']}")
        
        modules_to_test = [
            "liger_kernel.transformers.rope",
            "liger_kernel.transformers.swiglu",
            "liger_kernel.transformers.layer_norm",
        ]
        
        for module in modules_to_test:
            try:
                imported_module = importlib.import_module(module)
                print(f"imported {module} successfully")
                print(f"{module}.__file__: {imported_module.__file__}")
            except ImportError as e:
                print(f"Failed to import {module}: {e}")
        
        print("\nPackage structure:")
        if liger_kernel.__file__ is not None:
            package_path = os.path.dirname(liger_kernel.__file__)
            for root, dirs, files in os.walk(package_path):
                level = root.replace(package_path, '').count(os.sep)
                indent = '    ' * level
                print(f"{indent}{os.path.basename(root)}/")
                sub_indent = ' ' * 4 * (level + 1)
                for file in files:
                    print(f"{sub_indent}{file}")
        else:
            print(f"cant build package structure: liger_kernel.__file__ is {liger_kernel.__file__}")
                
    except ImportError as e:
        print(f"Failed to import liger_kernel: {e}")
    
    print("\npython path:")
    for path in sys.path:
        print(path)

if __name__ == "__main__":
    print(f"python version: {sys.version}")
    print(f"working dir: {os.getcwd()}")
    test_liger_kernel_imports("stable")
    print("\n==================================\n")
    test_liger_kernel_imports("nightly")
```

**Comment by lancerts** [comment]
> Joining here, having weird issues with the editable install as well, can't find a minimaln reproduction tho. Something is off though.

same here.

**Review by lancerts — APPROVED** [review]

**Pull request merged**
