### PR TITLE
Added H100 benchmarks

### PR DESCRIPTION
**Pull request by shimizust**
## Summary
- Added H100 benchmarks, using snake-case GPU name for directory name under each benchmark type
- Had to slightly increase test tolerances on H100

## Testing Done

- [x] run `make test` to ensure correctness
- [x] run `make checkstyle` to ensure code style
- [x] run `make test-convergence` to ensure convergence

```
$ make test
pytest --disable-warnings test/ --ignore=test/convergence
================================================================================ test session starts ================================================================================
platform linux -- Python 3.10.14, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/jobuser/Liger-Kernel
plugins: lipy-config-base-32.0.27, lipy-fabric-35.2.19, lipy-test-8.0.66, datadir-1.3.1
collected 114 items                                                                                                                                                                 

test/transformers/test_cross_entropy.py ..........................................................                                                                            [ 50%]
test/transformers/test_fused_linear_cross_entropy.py ......                                                                                                                   [ 56%]
test/transformers/test_geglu.py ........                                                                                                                                      [ 63%]
test/transformers/test_rms_norm.py ................                                                                                                                           [ 77%]
test/transformers/test_rope.py ............                                                                                                                                   [ 87%]
test/transformers/test_swiglu.py ........                                                                                                                                     [ 94%]
test/transformers/test_trainer_integration.py ...                                                                                                                             [ 97%]
test/transformers/test_transformers_monkey_patch.py .                                                                                                                         [ 98%]
test/triton/test_triton_monkey_patch.py ..                                                                                                                                    [100%]

=============================================================================== 114 passed in 35.04s ================================================================================
(.venv) jobuser [ ~/Liger-Kernel ]$ make test-convergence
HF_DATASETS_OFFLINE=1 pytest --disable-warnings test/convergence
================================================================================ test session starts ================================================================================
platform linux -- Python 3.10.14, pytest-7.1.2, pluggy-1.0.0
rootdir: /home/jobuser/Liger-Kernel
plugins: lipy-config-base-32.0.27, lipy-fabric-35.2.19, lipy-test-8.0.66, datadir-1.3.1
collected 6 items                                                                                                                                                                   

test/convergence/test_mini_models.py ....                                                                                                                                     [ 66%]
test/convergence/test_mini_models_no_logits.py ..                                                                                                                             [100%]

================================================================================ 6 passed in 22.96s =================================================================================

make checkstyle
flake8 . --exclude=.venv; flake8_status=$?; \
isort .; isort_status=$?; \
black .; black_status=$?; \
if [ $flake8_status -ne 0 ] || [ $isort_status -ne 0 ] || [ $black_status -ne 0 ]; then \
        exit 1; \
fi
Skipped 2 files
All done! ✨ 🍰 ✨
51 files left unchanged.
```

### CODE REVIEW

**Review by ByronHsu — COMMENTED** [review]
For this pr, we can focus the correctness + convergence test. We need some discussion for how to organize benchmark results on different hardware (your solution lgtm). Thanks!

**Comment by shimizust** [comment]
> For this pr, we can focus the correctness + convergence test. We need some discussion for how to organize benchmark results on different hardware (your solution lgtm). Thanks!

Separated the testing changes to here: https://github.com/linkedin/Liger-Kernel/pull/55

**Review by ByronHsu — COMMENTED** [review]
I am wondering if storing a bunch of HTML, PNG for different hardwares is a good idea in the long term. It will make git clone becomes slower and slower. However, the files seem to be relatively small so it should be also ok? Thoughts @lancerts @yundai424 ?

**Comment by ByronHsu** [comment]
Or we can just store the pure csv file

**Comment by yundai424** [comment]
I'm thinking if it's possible to save just the csv files and have some auto script to consolidate them into fewer plots (can even overlay a100 w/ h100 together). This way each git diff will be significantly smaller (just byte differents in csv cells and less image file change), to avoid carrying a heavy git history 🤔

**Comment by ByronHsu** [comment]
https://github.com/linkedin/Liger-Kernel/issues/56
created an good first issue

**Comment by ByronHsu** [comment]
Closed it for now, but we can keep the branch.

**Pull request closed without merging**
